import numpy as np
"""Configuration file for the generate_model_predictor.py script that allows you to generate
a certain model predictor from its parameters"""

n_kernels_GMM = 100   # Number of clusters of the GMM

threshold_neutral = 0.3  # Defines the threshold of the neutral configurations
""" If the threshold is 0.3, all those configurations that occur within the sequences with vas equal to 0 
 with a frequency greater than 0.3 will be considered neutral """

selected_lndks_idx = np.arange(66)  # Indexes of the landmarks to use for fitting GMM and description sequences

train_by_max_score = True  # Defines whether the model classifier must be generated by maximizing the
                           # resulting score as the gamma and regularization

regularization_parameter = 1  # Only to be used if train_by_max_score = False

gamma_parameter = 'scale'  # Only to be used if train_by_max_score = False

type_classifier = 'SVR'  # Indicates the type of the classifier ('SVR' or 'SVM')

dump_preliminary_clustering = False  # Defines whether preliminary clustering should be saved or not so that
                                     # it does not have to be recalculated in the future

"""If dump_preliminary_clustering = True, the preliminary clustering is saved in a .pickle file in the project folder 
'data/classifier/n_kernels/' with n=number of kernels of GMM (make sure that this path exists)"""

load_preliminary_clustering = False  # Defines whether a previously saved preliminary clustering should be used
"""If load_preliminary_clustering = True, the preliminary clustering that will be used will be that of the path
 'data/classifier/n_kernels/preliminary_clustering.pickle' with n=number of kernels of GMM 
 (make sure that this file exists)"""

save_histo_figures = False  # Defines if the histograms of the dataset sequences must be saved in their respective files
"""If save_histo_figures = True, the histograms are saved in the project folder
 'data/classifier/n_kernels/figures/histograms/' with n=number of kernels of GMM
 (make sure that this file exists)"""
