import numpy as np
"""Configuration file for the generate_model_predictor.py script that allows you to generate
a certain model predictor from its parameters"""

# Number of clusters of the GMM
n_kernels_GMM = 25

# Threshold of the neutral configurations
threshold_neutral = 0.01
""" If the threshold is 0.3, all those configurations that occur within the sequences with vas equal to 0 
 with a frequency greater than 0.3 will be considered neutral """

# Indexes of the landmarks to use for fitting GMM and description sequences
selected_lndks_idx = [5, 11, 19, 24, 37, 41, 56, 58]

# Defines whether the model classifier must be generated by maximizing the resulting score as the gamma and regularization
train_by_max_score = True

# Only to be used if train_by_max_score = False
regularization_parameter = 1

# Only to be used if train_by_max_score = False
gamma_parameter = 'scale'

# Indicates the type of the classifier ('SVR' or 'SVM')
type_classifier = 'SVR'

# Defines if the histograms of the dataset sequences must be saved in their respective files
save_histo_figures = False
"""If save_histo_figures = True, the histograms are saved in the project folder
 'data/classifier/n_kernels/figures/histograms/' with n=number of kernels of GMM
 (make sure that this file exists)"""

# Type of protocol to be used to evaluate the performance of the models
cross_val_protocol = "5-fold-cross-validation"
"""cross_val_protocol:  'Leave-One-Sequence-Out' or '5-fold-cross-validation' """
